---
atom:
  activities: https://git.oceanwing.com/user_name/project_name.atom?private_token=your_token_here
  issues: https://git.oceanwing.com/user_name/project_name/issues.atom?private_token=your_token_here
  development_commits: https://git.oceanwing.com/user_name/project_name/commits/develop.atom?private_token=your_token_here
last_read:
  activities: 2015-11-01 06:07:17.000000000 Z
  issues: 2015-11-01 11:02:44.000000000 Z
  development_commits: 2015-11-02 11:59:58.000000000 Z
